var searchData=
[
  ['complex16',['complex16',['../group__complex16__blas__level1.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__blas__level2.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__blas__level3.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__blas__testing.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__eig.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__lin.html',1,'']]],
  ['complex16',['complex16',['../group__complex16__matgen.html',1,'']]],
  ['complex16',['complex16',['../group__complex16GBauxiliary.html',1,'']]],
  ['complex16',['complex16',['../group__complex16GBcomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16GBsolve.html',1,'']]],
  ['complex16',['complex16',['../group__complex16GEauxiliary.html',1,'']]],
  ['complex16',['complex16',['../group__complex16GEcomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16GEeigen.html',1,'']]],
  ['complex16',['complex16',['../group__complex16GEsing.html',1,'']]],
  ['complex16',['complex16',['../group__complex16GEsolve.html',1,'']]],
  ['complex16',['complex16',['../group__complex16GTcomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16GTsolve.html',1,'']]],
  ['complex16',['complex16',['../group__complex16POauxiliary.html',1,'']]],
  ['complex16',['complex16',['../group__complex16POcomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16POsolve.html',1,'']]],
  ['complex16',['complex16',['../group__complex16PTcomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16PTsolve.html',1,'']]],
  ['complex16',['complex16',['../group__complex16SYauxiliary.html',1,'']]],
  ['complex16',['complex16',['../group__complex16SYcomputational.html',1,'']]],
  ['complex16',['complex16',['../group__complex16SYeigen.html',1,'']]],
  ['complex16',['complex16',['../group__complex16SYsolve.html',1,'']]],
  ['complex',['complex',['../group__complex__blas__level1.html',1,'']]],
  ['complex',['complex',['../group__complex__blas__level2.html',1,'']]],
  ['complex',['complex',['../group__complex__blas__level3.html',1,'']]],
  ['complex',['complex',['../group__complex__blas__testing.html',1,'']]],
  ['complex',['complex',['../group__complex__eig.html',1,'']]],
  ['complex',['complex',['../group__complex__lin.html',1,'']]],
  ['complex',['complex',['../group__complex__matgen.html',1,'']]],
  ['complex',['complex',['../group__complexGBauxiliary.html',1,'']]],
  ['complex',['complex',['../group__complexGBcomputational.html',1,'']]],
  ['complex',['complex',['../group__complexGBsolve.html',1,'']]],
  ['complex',['complex',['../group__complexGEauxiliary.html',1,'']]],
  ['complex',['complex',['../group__complexGEcomputational.html',1,'']]],
  ['complex',['complex',['../group__complexGEeigen.html',1,'']]],
  ['complex',['complex',['../group__complexGEsing.html',1,'']]],
  ['complex',['complex',['../group__complexGEsolve.html',1,'']]],
  ['complex',['complex',['../group__complexGTcomputational.html',1,'']]],
  ['complex',['complex',['../group__complexGTsolve.html',1,'']]],
  ['complex',['complex',['../group__complexPOauxiliary.html',1,'']]],
  ['complex',['complex',['../group__complexPOcomputational.html',1,'']]],
  ['complex',['complex',['../group__complexPOsolve.html',1,'']]],
  ['complex',['complex',['../group__complexPTcomputational.html',1,'']]],
  ['complex',['complex',['../group__complexPTsolve.html',1,'']]],
  ['complex',['complex',['../group__complexSYauxiliary.html',1,'']]],
  ['complex',['complex',['../group__complexSYcomputational.html',1,'']]],
  ['complex',['complex',['../group__complexSYeigen.html',1,'']]],
  ['complex',['complex',['../group__complexSYsolve.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computationalGB.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computationalGE.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computationalGT.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computationalPO.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computationalPT.html',1,'']]],
  ['computational_20routines',['Computational routines',['../group__computationalSY.html',1,'']]]
];
